#include "export.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>

/* Seconds of motion to sample when nothing is driving the mechanism and it
 * is just falling/swinging under gravity. */
#define GRAVITY_SAMPLE_SECONDS 3.0
/* Upper bound on the simulation step used while sampling. The recorded
 * frames can be far apart in time (a slow motor makes one revolution take
 * many seconds), and stepping that coarsely would let the solver lose the
 * mechanism's branch, so each sample is reached via several small steps. */
#define MAX_SUBSTEP_SECONDS (1.0 / 240.0)

/* How long one full revolution of the fastest motor takes, or 0 if nothing
 * is turning. */
static double driven_period_seconds(const Mechanism *m) {
    double fastest = 0.0;
    for (int li = 0; li < m->link_count; li++) {
        const Link *l = &m->links[li];
        if (!l->alive || !l->is_driven) continue;
        double speed = fabs(l->motor_speed_deg_s);
        if (speed > fastest) fastest = speed;
    }
    if (fastest <= 0.0) return 0.0;
    return 360.0 / fastest;
}

bool export_blender_script(const Mechanism *m, SolverParams params, const char *filepath) {
    FILE *f = fopen(filepath, "w");
    if (!f) return false;

    /* Index the connectors we actually export, so the per-frame position
     * table lines up with the joint list regardless of deleted ids. */
    int *joint_ids = malloc((size_t)(m->connector_count > 0 ? m->connector_count : 1) * sizeof(int));
    int joint_count = 0;
    for (int i = 0; i < m->connector_count; i++) {
        if (m->connectors[i].alive) joint_ids[joint_count++] = i;
    }

    /* Simulate a private copy so the live mechanism is untouched. */
    Mechanism sim;
    mechanism_clone(m, &sim);
    solver_freeze(&sim);

    double period = driven_period_seconds(&sim);
    bool driven = (period > 0.0);
    double duration = driven ? period : GRAVITY_SAMPLE_SECONDS;
    if (!driven && !mechanism_has_driven_link(&sim) &&
        params.gravity.x == 0.0 && params.gravity.y == 0.0) {
        /* Nothing would move at all; match the app, which runs a motorless
         * mechanism under gravity. */
        params.gravity = (Vec2){ 0.0, 400.0 };
    }

    double frame_dt = duration / (double)EXPORT_FRAMES;
    int substeps = (int)ceil(frame_dt / MAX_SUBSTEP_SECONDS);
    if (substeps < 1) substeps = 1;
    double substep_dt = frame_dt / (double)substeps;

    Vec2 *samples = malloc((size_t)EXPORT_FRAMES * (size_t)(joint_count > 0 ? joint_count : 1) * sizeof(Vec2));
    int recorded = 0;
    bool jammed = false;

    for (int fr = 0; fr < EXPORT_FRAMES; fr++) {
        if (fr > 0) {
            for (int s = 0; s < substeps; s++) solver_advance(&sim, substep_dt, params);
            if (solver_has_length_violation(&sim, params.length_tol_abs, params.length_tol_rel)) {
                jammed = true;
                break; /* stop at the bind; don't record impossible geometry */
            }
        }
        for (int j = 0; j < joint_count; j++) {
            samples[(size_t)recorded * (size_t)joint_count + j] = sim.connectors[joint_ids[j]].pos;
        }
        recorded++;
    }

    fprintf(f,
        "import bpy\n"
        "import mathutils\n"
        "\n"
        "# Generated by Linkage Design (mechanism export).\n"
        "# Convention: 1 mechanism world unit = 1 mm.\n"
        "# Press Space in Blender to play the animation.\n"
        "\n"
        "ROD_RADIUS_MM = 3.0  # link/rod cylinder radius -- edit to taste before running\n"
        "JOINT_MARKER_RADIUS_MM = ROD_RADIUS_MM * 1.5\n"
        "\n");

    fprintf(f, "FRAME_COUNT = %d\n", recorded);
    fprintf(f, "DURATION_SECONDS = %.6f\n", duration * ((double)(recorded > 1 ? recorded - 1 : 1) / (double)(EXPORT_FRAMES - 1)));
    if (jammed) {
        fprintf(f, "# NOTE: the mechanism bound up partway; the animation stops where it jammed.\n");
    }
    fprintf(f, "\n");

    /* Joint names, in the same order as each frame's position row. */
    fprintf(f, "JOINTS = [\n");
    for (int j = 0; j < joint_count; j++) {
        int cid = joint_ids[j];
        fprintf(f, "    (\"%s_%d\", %s),\n",
                m->connectors[cid].is_anchor ? "Anchor" : "Joint", cid,
                m->connectors[cid].is_anchor ? "True" : "False");
    }
    fprintf(f, "]\n\n");

    /* Rods, referring to joints by their index in JOINTS. */
    fprintf(f, "RODS = [\n");
    for (int li = 0; li < m->link_count; li++) {
        const Link *l = &m->links[li];
        if (!l->alive) continue;
        int k = l->connector_count;
        for (int i = 0; i < k; i++) {
            for (int j = i + 1; j < k; j++) {
                int ci = l->connector_ids[i], cj = l->connector_ids[j];
                int slot_i = -1, slot_j = -1;
                for (int s = 0; s < joint_count; s++) {
                    if (joint_ids[s] == ci) slot_i = s;
                    if (joint_ids[s] == cj) slot_j = s;
                }
                if (slot_i < 0 || slot_j < 0) continue;
                fprintf(f, "    (\"Link%d_c%dc%d\", %d, %d),\n", li, ci, cj, slot_i, slot_j);
            }
        }
    }
    fprintf(f, "]\n\n");

    /* One row of joint positions per animation frame. */
    fprintf(f, "FRAMES = [\n");
    for (int fr = 0; fr < recorded; fr++) {
        fprintf(f, "    [");
        for (int j = 0; j < joint_count; j++) {
            Vec2 p = samples[(size_t)fr * (size_t)joint_count + j];
            fprintf(f, "(%.4f,%.4f)%s", p.x, p.y, (j + 1 < joint_count) ? "," : "");
        }
        fprintf(f, "],\n");
    }
    fprintf(f, "]\n\n");

    fprintf(f,
        "scene = bpy.context.scene\n"
        "scene.unit_settings.system = 'METRIC'\n"
        "scene.unit_settings.length_unit = 'MILLIMETERS'\n"
        "scene.frame_start = 1\n"
        "scene.frame_end = max(FRAME_COUNT, 1)\n"
        "if FRAME_COUNT > 1 and DURATION_SECONDS > 0.0:\n"
        "    # Play back at the same rate the mechanism actually runs.\n"
        "    scene.render.fps = 60\n"
        "    scene.render.fps_base = 60.0 * DURATION_SECONDS / (FRAME_COUNT - 1)\n"
        "\n"
        "\n"
        "def mm(v):\n"
        "    return v / 1000.0\n"
        "\n"
        "\n"
        "def make_joint(name, is_anchor):\n"
        "    bpy.ops.object.empty_add(\n"
        "        type='PLAIN_AXES' if is_anchor else 'SPHERE',\n"
        "        radius=mm(JOINT_MARKER_RADIUS_MM), location=(0.0, 0.0, 0.0))\n"
        "    obj = bpy.context.object\n"
        "    obj.name = name\n"
        "    return obj\n"
        "\n"
        "\n"
        "def make_rod(name):\n"
        "    # Unit-depth cylinder: its length is set per frame via scale.z,\n"
        "    # which also lets variable-length links animate correctly.\n"
        "    bpy.ops.mesh.primitive_cylinder_add(radius=mm(ROD_RADIUS_MM), depth=1.0,\n"
        "                                        location=(0.0, 0.0, 0.0))\n"
        "    obj = bpy.context.object\n"
        "    obj.name = name\n"
        "    obj.rotation_mode = 'QUATERNION'\n"
        "    return obj\n"
        "\n"
        "\n"
        "joints = [make_joint(name, is_anchor) for (name, is_anchor) in JOINTS]\n"
        "rods = [(make_rod(name), i, j) for (name, i, j) in RODS]\n"
        "\n"
        "for frame_index, positions in enumerate(FRAMES):\n"
        "    frame = frame_index + 1\n"
        "    for obj, (x, y) in zip(joints, positions):\n"
        "        obj.location = (mm(x), mm(y), 0.0)\n"
        "        obj.keyframe_insert('location', frame=frame)\n"
        "    for obj, i, j in rods:\n"
        "        p0 = mathutils.Vector((mm(positions[i][0]), mm(positions[i][1]), 0.0))\n"
        "        p1 = mathutils.Vector((mm(positions[j][0]), mm(positions[j][1]), 0.0))\n"
        "        direction = p1 - p0\n"
        "        length = direction.length\n"
        "        obj.location = (p0 + p1) / 2.0\n"
        "        if length > 1e-12:\n"
        "            obj.rotation_quaternion = direction.to_track_quat('Z', 'Y')\n"
        "        obj.scale = (1.0, 1.0, max(length, 1e-9))\n"
        "        obj.keyframe_insert('location', frame=frame)\n"
        "        obj.keyframe_insert('rotation_quaternion', frame=frame)\n"
        "        obj.keyframe_insert('scale', frame=frame)\n"
        "\n"
        "def iter_fcurves(action):\n"
        "    # Blender <4.4 exposes action.fcurves directly; 4.4+ moved them\n"
        "    # into slotted actions (layers -> strips -> channelbags).\n"
        "    fcurves = getattr(action, 'fcurves', None)\n"
        "    if fcurves is not None:\n"
        "        for fcurve in fcurves:\n"
        "            yield fcurve\n"
        "        return\n"
        "    for layer in getattr(action, 'layers', []):\n"
        "        for strip in getattr(layer, 'strips', []):\n"
        "            for channelbag in getattr(strip, 'channelbags', []):\n"
        "                for fcurve in channelbag.fcurves:\n"
        "                    yield fcurve\n"
        "\n"
        "\n"
        "# Constant-speed motion should not ease in and out between samples.\n"
        "# The motion is already baked into the keyframes, so treat this as a\n"
        "# nicety: never let an API change here break the whole import.\n"
        "try:\n"
        "    for obj in joints + [rod for (rod, _i, _j) in rods]:\n"
        "        action = obj.animation_data.action if obj.animation_data else None\n"
        "        if action is None:\n"
        "            continue\n"
        "        for fcurve in iter_fcurves(action):\n"
        "            for kp in fcurve.keyframe_points:\n"
        "                kp.interpolation = 'LINEAR'\n"
        "except Exception as exc:\n"
        "    print('Linkage Design: could not set linear interpolation (%%s); '\n"
        "          'the animation is still correct.' %% exc)\n"
        "\n"
        "scene.frame_set(1)\n"
        "print('Linkage Design: built %%d joints, %%d rods, %%d frames.'\n"
        "      %% (len(joints), len(rods), FRAME_COUNT))\n");

    fclose(f);
    free(samples);
    free(joint_ids);
    mechanism_free(&sim);
    return true;
}
