#include "export.h"

#include <stdio.h>

bool export_blender_script(const Mechanism *m, const char *filepath) {
    FILE *f = fopen(filepath, "w");
    if (!f) return false;

    fprintf(f,
        "import bpy\n"
        "import mathutils\n"
        "\n"
        "# Generated by Linkage Design (mechanism export).\n"
        "# Convention: 1 mechanism world unit = 1 mm.\n"
        "\n"
        "bpy.context.scene.unit_settings.system = 'METRIC'\n"
        "bpy.context.scene.unit_settings.length_unit = 'MILLIMETERS'\n"
        "\n"
        "ROD_RADIUS_MM = 3.0  # link/rod cylinder radius -- edit to taste before running\n"
        "JOINT_MARKER_RADIUS_MM = ROD_RADIUS_MM * 1.5\n"
        "\n"
        "\n"
        "def add_rod(name, x0, y0, x1, y1, radius_mm):\n"
        "    p0 = mathutils.Vector((x0 / 1000.0, y0 / 1000.0, 0.0))\n"
        "    p1 = mathutils.Vector((x1 / 1000.0, y1 / 1000.0, 0.0))\n"
        "    direction = p1 - p0\n"
        "    length = direction.length\n"
        "    if length < 1e-9:\n"
        "        return None\n"
        "    bpy.ops.mesh.primitive_cylinder_add(radius=radius_mm / 1000.0, depth=length, location=(p0 + p1) / 2.0)\n"
        "    obj = bpy.context.object\n"
        "    obj.name = name\n"
        "    obj.rotation_mode = 'QUATERNION'\n"
        "    obj.rotation_quaternion = direction.to_track_quat('Z', 'Y')\n"
        "    return obj\n"
        "\n"
        "\n"
        "def add_joint(name, x, y):\n"
        "    bpy.ops.object.empty_add(type='PLAIN_AXES', radius=JOINT_MARKER_RADIUS_MM / 1000.0,\n"
        "                             location=(x / 1000.0, y / 1000.0, 0.0))\n"
        "    bpy.context.object.name = name\n"
        "    return bpy.context.object\n"
        "\n"
        "\n");

    fprintf(f, "# Joints (%d)\n", m->connector_count);
    for (int i = 0; i < m->connector_count; i++) {
        const Connector *c = &m->connectors[i];
        if (!c->alive) continue;
        fprintf(f, "add_joint(\"%s_%d\", %.6f, %.6f)\n",
                c->is_anchor ? "Anchor" : "Joint", i, c->pos.x, c->pos.y);
    }

    fprintf(f, "\n# Links (%d)\n", m->link_count);
    for (int li = 0; li < m->link_count; li++) {
        const Link *l = &m->links[li];
        if (!l->alive) continue;
        for (int i = 0; i < l->connector_count; i++) {
            for (int j = i + 1; j < l->connector_count; j++) {
                int ci = l->connector_ids[i];
                int cj = l->connector_ids[j];
                Vec2 a = m->connectors[ci].pos;
                Vec2 b = m->connectors[cj].pos;
                fprintf(f, "add_rod(\"Link%d_c%dc%d\", %.6f, %.6f, %.6f, %.6f, ROD_RADIUS_MM)\n",
                        li, ci, cj, a.x, a.y, b.x, b.y);
            }
        }
    }

    fclose(f);
    return true;
}
